ibm-apic-instance:
  ibmapicinstance:
    name: apic-cluster
    spec:
      license:
        accept: true
        use: nonproduction
        license: L-RJON-CEBL97
      version: 10.0.5.1
      profile: n1xc10.m48
      allowUpgrade: true
